categories: Categories
search: Search
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
prev: ← Previous Posts
next: Next Posts →
comment: Comments
archive_a: Archive
archive_b: "Archives: %s"
page: Page %d
recent_posts: Recent Posts
newer: ← Newer
older: Older →
share: Share
powered_by: Powered by
rss_feed: RSS Feed
category: Category
tag: Tag
